language: node_js
node_js:
  - "stable"
script:
  - npm test
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
  - nyc report --reporter=text-lcov | coveralls
addons:
  code_climate:
    repo_token:
      secure: "3dde50e04b397704e4b66fc21220fc31ba41d68f78dc088cf717ff403bed1a16"